### ISSUE TITLE
rig restart panic in 2.0-rc1

### ISSUE THREAD

**Issue by grayside** [phase2/rig#113]
```
$> rig restart
[INFO] Restarting Outrigger machine 'dev' and services
[INFO] Stopping machine 'dev'
[INFO] Cleaning up local networking (may require your admin password)
Password:
[INFO] Machine 'dev' stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x1167ac6]

goroutine 1 [running]:
github.com/phase2/rig/vendor/github.com/urfave/cli.lookupGlobalFlagSet(0x13eb404, 0x5, 0x0, 0x26741c6f7)
	/go/src/github.com/phase2/rig/vendor/github.com/urfave/cli/context.go:228 +0x26
github.com/phase2/rig/vendor/github.com/urfave/cli.(*Context).GlobalBool(0x0, 0x13eb404, 0x5, 0x164a760)
	/go/src/github.com/phase2/rig/vendor/github.com/urfave/cli/flag_generated.go:40 +0x3f
github.com/phase2/rig/util.shouldNotify(0x0, 0xc420080e40)
	/go/src/github.com/phase2/rig/util/notify.go:56 +0x40
github.com/phase2/rig/util.NotifySuccess(0x0, 0xc42012de00, 0x15)
	/go/src/github.com/phase2/rig/util/notify.go:41 +0x2f
github.com/phase2/rig/commands.(*BaseCommand).Success(0xc4200a5850, 0xc42012de00, 0x15, 0x1, 0x1)
	/go/src/github.com/phase2/rig/commands/command.go:44 +0xed
github.com/phase2/rig/commands.(*Stop).StopOutrigger(0xc4200a5850, 0x0, 0x2f)
	/go/src/github.com/phase2/rig/commands/stop.go:71 +0x332
github.com/phase2/rig/commands.(*Stop).Run(0xc4200a5850, 0xc4200c2580, 0x2e, 0xc4200a5840)
	/go/src/github.com/phase2/rig/commands/stop.go:36 +0x2b
github.com/phase2/rig/commands.(*Restart).Run(0xc420050500, 0xc4200c2580, 0xc420158350, 0xc4200a5928)
	/go/src/github.com/phase2/rig/commands/restart.go:38 +0x170
github.com/phase2/rig/commands.(*Restart).Run-fm(0xc4200c2580, 0x0, 0x0)
	/go/src/github.com/phase2/rig/commands/restart.go:23 +0x34
github.com/phase2/rig/vendor/github.com/urfave/cli.HandleAction(0x13743e0, 0xc420046f10, 0xc4200c2580, 0xc42012e900, 0x0)
	/go/src/github.com/phase2/rig/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/phase2/rig/vendor/github.com/urfave/cli.Command.Run(0x13ebc01, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13f29f4, 0x1a, 0x0, ...)
	/go/src/github.com/phase2/rig/vendor/github.com/urfave/cli/command.go:210 +0xa95
github.com/phase2/rig/vendor/github.com/urfave/cli.(*App).Run(0xc420076ea0, 0xc42000a080, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/phase2/rig/vendor/github.com/urfave/cli/app.go:255 +0x6f8
main.main()
	/go/src/github.com/phase2/rig/cmd/main.go:64 +0x12b1
```

**Comment by febbraro** [comment]
When we implemented notifcations, `Before` is now capturing the `cli.Context` so we dont have to pass it around everywhere.  Commands that delegate to other commands were not updated to populate that `cli.Context` on `BaseCommand` correctly. Working on a PR for that right now.
